### ISSUE TITLE
Support - Product booking with WCFM plugin 

### ISSUE THREAD

**Issue by odaymusic** [AppCheap/roadmap#72]
please add booking with WCFM 

- [x] Support https://bookingwp.com/

**Comment by Arsl143** [comment]
Please add booking with wcfm ,i need too,

**Comment by Arsl143** [comment]
@dangtienngoc Please add

**Comment by msurchy** [comment]
This will be good feature.

**Comment by bakpaorabbit** [comment]
hi @dangtienngoc , just to let you know that bookingwp plugin is bundled with woocommerce product add on. so when you enable this plugin, it will disable plugin "woocommerce product add-on" . I hope the product add on will work well.

**Comment by odaymusic** [comment]
good update <3 <3 <3 .. please update audio provider to waves style

**Comment by bakpaorabbit** [comment]
@dangtienngoc you miss something here.
as I told you that BookingWp is including Woocommerce Product Add Ons. So when you have Individual WooCommerce Products Add Ons plugin, it will deactivated automatically because BookingWp built in WooCommerce Products Add On.

The problem is, when you use BookingWP. all simple product with Add Ons will not show in app.

I make it simple. So when we :

1. Install woocommerce product add ons = you cannot use bookingwp

2. Install bookingwp = you cannot use product add on even though the plugin already includes the same plugin : woocommerce product add ons. If you use, then all simple product with add ons will not show in the app

Need solution to use BookingWP but with featured Add Ons.
